- title: Watch your Up-Convolution - CNN Based Generative Deep Neural Networks are Failing to Reproduce Spectral Distributions
  authors: 
    - Ricard Durall
    - Margret Keuper
    - Janis Keuper
  link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Durall_Watch_Your_Up-Convolution_CNN_Based_Generative_Deep_Neural_Networks_Are_CVPR_2020_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition 
  date: 2020-06-01
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Durall_Watch_Your_Up-Convolution_CNN_Based_Generative_Deep_Neural_Networks_Are_CVPR_2020_paper.pdf
    - type: source
      link: https://github.com/cc-hpc-itwm/UpConv
  image: images/cvpr_20.jpg
  tags:
    - GAN
    - robustness
 
- title: CNN Filter DB - An Empirical Investigation of Trained Convolutional Filters
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://openaccess.thecvf.com/content/CVPR2022/papers/Gavrikov_CNN_Filter_DB_An_Empirical_Investigation_of_Trained_Convolutional_Filters_CVPR_2022_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition 
  date: 2022-06-01
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content/CVPR2022/papers/Gavrikov_CNN_Filter_DB_An_Empirical_Investigation_of_Trained_Convolutional_Filters_CVPR_2022_paper.pdf
    - type: source
      link: https://github.com/paulgavrikov/CNN-Filter-DB
  image: images/cvpr_22.png
  tags:
    - ORAL
    - CNN
    - robustness
    
- title: FrequencyLowCut Pooling--Plug & Play against Catastrophic Overfitting
  authors: 
    - Julia Grabinski
    - Steffen Jung
    - Janis Keuper
    - Margret Keuper
  link: https://arxiv.org/pdf/2204.00491
  publisher: ECCV 2022 - 17th European Conference, Tel Aviv, Israel, October 23-27, 2022, Proceedings
  date: 2022-10-01
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2204.00491
    - type: source
      link: https://github.com/GeJulia/flc_pooling
  image: images/eccv_22.png
  tags:
    - CNN
    - robustness    

- title: Robust Models are less Over-Confident
  authors: 
    - Julia Grabinski
    - Paul Gavrikov
    - Janis Keuper
    - Margret Keuper
  link: https://arxiv.org/pdf/2210.05938
  publisher: NeurIPS 22, proceedings of the thirty-sixth Conference on Neural Information Processing Systems 
  date: 2022-11-01
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2210.05938
    - type: source
      link: https://github.com/GeJulia/robustness_confidences_evaluation
  image: images/neurips_22.png
  tags:
    - CNN
    - robustness    
