# WARNING: do NOT change month and day at the date -> Bug! Changing the year is fine


- title: Watch your Up-Convolution - CNN Based Generative Deep Neural Networks are Failing to Reproduce Spectral Distributions
  date: 2020-6-1 
  authors: 
    - Ricard Durall
    - Margret Keuper
    - Janis Keuper
  link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Durall_Watch_Your_Up-Convolution_CNN_Based_Generative_Deep_Neural_Networks_Are_CVPR_2020_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition 
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Durall_Watch_Your_Up-Convolution_CNN_Based_Generative_Deep_Neural_Networks_Are_CVPR_2020_paper.pdf
    - type: source
      link: https://github.com/cc-hpc-itwm/UpConv
  image: images/cvpr_20.jpg
  tags:
    - GAN
    - robustness
 
- title: CNN Filter DB - An Empirical Investigation of Trained Convolutional Filters
  date: 2022-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://openaccess.thecvf.com/content/CVPR2022/papers/Gavrikov_CNN_Filter_DB_An_Empirical_Investigation_of_Trained_Convolutional_Filters_CVPR_2022_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition 
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content/CVPR2022/papers/Gavrikov_CNN_Filter_DB_An_Empirical_Investigation_of_Trained_Convolutional_Filters_CVPR_2022_paper.pdf
    - type: source
      link: https://github.com/paulgavrikov/CNN-Filter-DB
    - type: youtube
      link: https://github.com/paulgavrikov/CNN-Filter-DB
  image: images/cvpr_22_oral.png
  tags:
    - ORAL
    - CNN
    - robustness
    
- title: FrequencyLowCut Pooling--Plug & Play against Catastrophic Overfitting
  date: 2022-6-1
  authors: 
    - Julia Grabinski
    - Steffen Jung
    - Janis Keuper
    - Margret Keuper
  link: https://arxiv.org/pdf/2204.00491
  publisher: ECCV 2022 - Proceedings of the 17th European Conference, Tel Aviv, Israel
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2204.00491
    - type: source
      link: https://github.com/GeJulia/flc_pooling
  image: images/eccv_22.png
  tags:
    - CNN
    - robustness    

- title: Learning Where To Look--Generative NAS is Surprisingly Efficient
  date: 2022-6-1
  authors: 
    - Jovita Lukasik
    - Steffen Jung
    - Margret Keuper
  link: https://arxiv.org/pdf/2203.08734.pdf
  publisher: ECCV 2022 - Proceedings of the 17th European Conference, Tel Aviv, Israel
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2203.08734.pdf
    - type: source
      link: https://github.com/jovitalukasik/AG-Net
  image: images/eccv_22.png
  tags:
    - NAS  

- title: Robust Models are less Over-Confident
  date: 2022-6-1
  authors: 
    - Julia Grabinski
    - Paul Gavrikov
    - Janis Keuper
    - Margret Keuper
  link: https://arxiv.org/pdf/2210.05938
  publisher: NeurIPS 22, proceedings of the thirty-sixth Conference on Neural Information Processing Systems 
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2210.05938
    - type: source
      link: https://github.com/GeJulia/robustness_confidences_evaluation
  image: images/neurips_22.png
  tags:
    - CNN
    - robustness    

- title: Trading off Image Quality for Robustness is not Necessary with Regularized Deterministic Autoencoders
  date: 2022-6-1
  authors: 
    - Amrutha Saseendran
    - Kathrin Skubch
    - Margret Keuper
  link: https://pure.mpg.de/rest/items/item_3473164/component/file_3473165/content
  publisher: NeurIPS 22, proceedings of the thirty-sixth Conference on Neural Information Processing Systems 
  extra-links:
    - type: preprint
      link: https://pure.mpg.de/rest/items/item_3473164/component/file_3473165/content
  image: images/neurips_22.png
  tags:
    - robustness    
