- title: Watch your Up-Convolution - CNN Based Generative Deep Neural Networks are Failing to Reproduce Spectral Distributions
  authors: 
    - Ricard Durall
    - Margret Keuper
    - Janis Keuper
  link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Durall_Watch_Your_Up-Convolution_CNN_Based_Generative_Deep_Neural_Networks_Are_CVPR_2020_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition 
  date: 2020-6-1
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Durall_Watch_Your_Up-Convolution_CNN_Based_Generative_Deep_Neural_Networks_Are_CVPR_2020_paper.pdf
    - type: source
      link: https://github.com/cc-hpc-itwm/UpConv
  image: images/cvpr_20.jpg
  tags:
    - GAN
    - robustness
 
