# WARNINGS:
# 1) do NOT change month and day at the date -> Bug! Changing the year is fine
# 2) NO ":" in titles -> will break yaml file

#-------------------------
# 2020
#-------------------------
- title: Watch your Up-Convolution - CNN Based Generative Deep Neural Networks are Failing to Reproduce Spectral Distributions
  date: 2020-6-1 
  authors: 
    - Ricard Durall
    - Margret Keuper
    - Janis Keuper
  link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Durall_Watch_Your_Up-Convolution_CNN_Based_Generative_Deep_Neural_Networks_Are_CVPR_2020_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR 2020)
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Durall_Watch_Your_Up-Convolution_CNN_Based_Generative_Deep_Neural_Networks_Are_CVPR_2020_paper.pdf
    - type: source
      link: https://github.com/cc-hpc-itwm/UpConv
  image: images/cvpr_20.jpg
  tags:
    - GAN
    - robustness

- title: Extracting horizon surfaces from 3D seismic data using deep learning
  date: 2020-6-1
  authors: 
    - Valentin Tschannen
    - Matthias Delescluse
    - Norman Ettrich
    - Janis Keuper
  link: https://library.seg.org/doi/pdf/10.1190/geo2019-0569.1
  publisher: Geophysics - Journal of the Society of Exploration Geophysicists and American Association of Petroleum Geologists
  extra-links:
    - type: preprint
      link: https://library.seg.org/doi/pdf/10.1190/geo2019-0569.1
  image: images/seg.png
  tags:
    - Geophysics
    - CNN

#-------------------------
# 2021
#-------------------------

- title: Smooth variational graph embeddings for efficient neural architecture search
  date: 2021-6-1
  authors: 
    - Jovita Lukasik
    - David Friede
    - Arber Zela
    - Frank Hutter
    - Margret Keuper
    
  link: https://arxiv.org/pdf/2010.04683
  publisher: Proceedings of the Nineth International Conference on Learning Representations (ICLR 21)
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2010.04683
    - type: source
      link: https://github.com/jovitalukasik/SVGe
  image: images/iclr_22.png
  tags:
    - NAS

- title: Shape your Space - A Gaussian Mixture Regularization Approach to Deterministic Autoencoders
  date: 2021-6-1
  authors: 
    - Amrutha Saseendran
    - Kathrin Skubch
    - Stefan Falkner
    - Margret Keuper
  link: https://proceedings.neurips.cc/paper/2021/file/3c057cb2b41f22c0e740974d7a428918-Paper.pdf
  publisher: NeurIPS 21, proceedings of the thirty-sixth Conference on Neural Information Processing Systems 
  extra-links:
    - type: preprint
      link: https://proceedings.neurips.cc/paper/2021/file/3c057cb2b41f22c0e740974d7a428918-Paper.pdf
  image: images/neurips_22.png
  tags:
    - VAE    

- title: Multi-Class Multi-Instance Count Conditioned Adversarial Image Generation
  date: 2021-6-1
  authors: 
    - Amrutha Saseendran
    - Kathrin Skubch
    - Margret Keuper
  link: https://openaccess.thecvf.com/content/ICCV2021/papers/Saseendran_Multi-Class_Multi-Instance_Count_Conditioned_Adversarial_Image_Generation_ICCV_2021_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR 2021)
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content/ICCV2021/papers/Saseendran_Multi-Class_Multi-Instance_Count_Conditioned_Adversarial_Image_Generation_ICCV_2021_paper.pdf
  image: images/cvpr_21.jpg
  tags:
    - VAE
    - robustness


- title: Spectral distribution aware image generation
  date: 2021-6-1
  authors: 
    - Steffen Jung
    - Margret Keuper
  link: https://ojs.aaai.org/index.php/AAAI/article/view/16267/16074
  publisher: Geophysics - Journal of the Society of Exploration Geophysicists and American Association of Petroleum Geologists
  extra-links:
    - type: preprint
      link: https://ojs.aaai.org/index.php/AAAI/article/view/16267/16074
  image: images/aaai.jpg
  tags:
    - Geophysics
    - CNN
    
  - title: An Empirical Investigation of Model-to-Model Distribution Shifts in Trained Convolutional Filters
  date: 2021-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://arxiv.org/abs/2201.08465
  publisher: NeurIPS 22 Workshop - Distribution shifts: connecting methods and applications (DistShift)
  extra-links:
    - type: preprint
      link: https://arxiv.org/abs/2201.08465
  tags:
    - CNN

#-------------------------
# 2022
#-------------------------

- title: Surrogate NAS benchmarks - Going beyond the limited search spaces of tabular NAS benchmarks
  date: 2022-6-1
  authors: 
    - Arber Zela
    - Julien Niklas Siems
    - Lucas Zimmer
    - Jovita Lukasik
    - Margret Keuper
    - Frank Hutter
  link: https://pure.mpg.de/rest/items/item_3404264/component/file_3404265/content
  publisher: Proceedings of the Tenth International Conference on Learning Representations (ICLR 22)
  extra-links:
    - type: preprint
      link: https://pure.mpg.de/rest/items/item_3404264/component/file_3404265/content
  image: images/iclr_22.png
  tags:
    - NAS

- title: Higher-Order Multicuts for Geometric Model Fitting and Motion Segmentation
  date: 2022-6-1
  authors: 
    - Evgeny Levinkov
    - Amirhossein Kardoost
    - Bjoern Andres
    - Margret Keuper
  link: IEEE Transactions on Pattern Analysis and Machine Intelligence
  publisher: IEEE Transactions on Pattern Analysis and Machine Intelligence
  extra-links:
    - type: preprint
      link: IEEE Transactions on Pattern Analysis and Machine Intelligence
  image: images/tpami.png
  tags:
    - Multicut
    - Segmentation

- title: CNN Filter DB - An Empirical Investigation of Trained Convolutional Filters
  date: 2022-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://openaccess.thecvf.com/content/CVPR2022/papers/Gavrikov_CNN_Filter_DB_An_Empirical_Investigation_of_Trained_Convolutional_Filters_CVPR_2022_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR 2022)
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content/CVPR2022/papers/Gavrikov_CNN_Filter_DB_An_Empirical_Investigation_of_Trained_Convolutional_Filters_CVPR_2022_paper.pdf
    - type: source
      link: https://github.com/paulgavrikov/CNN-Filter-DB
    - type: youtube
      link: https://github.com/paulgavrikov/CNN-Filter-DB
    - type: website
      link: https://towardsdatascience.com/what-makes-the-convolutions-of-robust-vision-models-special-5f9c1a0c5bb5
  image: images/cvpr_22_oral.png
  tags:
    - ORAL
    - CNN
    - robustness

- title: Adversarial Robustness Through the Lens of Convolutional Filters
  date: 2022-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://openaccess.thecvf.com/content/CVPR2022W/ArtOfRobust/html/Gavrikov_Adversarial_Robustness_Through_the_Lens_of_Convolutional_Filters_CVPRW_2022_paper.html
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition Workshops (CVPRW 2022)
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content/CVPR2022W/ArtOfRobust/html/Gavrikov_Adversarial_Robustness_Through_the_Lens_of_Convolutional_Filters_CVPRW_2022_paper.html
    - type: source
      link: https://github.com/paulgavrikov/cvpr22w_RobustnessThroughTheLens
    - type: website
      link: https://towardsdatascience.com/what-makes-the-convolutions-of-robust-vision-models-special-5f9c1a0c5bb5
  tags:
    - CNN
    - robustness
    
 - title: Does Medical Imaging learn different Convolution Filters?
  date: 2022-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://arxiv.org/abs/2210.13799
  publisher: NeurIPS 22 Workshop - Medical Imaging meets NeurIPS
  extra-links:
    - type: preprint
      link: https://arxiv.org/abs/2210.13799
  tags:
    - CNN
    - medical imaging
    
- title: FrequencyLowCut Pooling--Plug & Play against Catastrophic Overfitting
  date: 2022-6-1
  authors: 
    - Julia Grabinski
    - Steffen Jung
    - Janis Keuper
    - Margret Keuper
  link: https://arxiv.org/pdf/2204.00491
  publisher: ECCV 2022 - Proceedings of the 17th European Conference, Tel Aviv, Israel
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2204.00491
    - type: source
      link: https://github.com/GeJulia/flc_pooling
  image: images/eccv_22.png
  tags:
    - CNN
    - robustness    

- title: Learning Where To Look--Generative NAS is Surprisingly Efficient
  date: 2022-6-1
  authors: 
    - Jovita Lukasik
    - Steffen Jung
    - Margret Keuper
  link: https://arxiv.org/pdf/2203.08734.pdf
  publisher: ECCV 2022 - Proceedings of the 17th European Conference, Tel Aviv, Israel
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2203.08734.pdf
    - type: source
      link: https://github.com/jovitalukasik/AG-Net
  image: images/eccv_22.png
  tags:
    - NAS  

- title: Robust Models are less Over-Confident
  date: 2022-6-1
  authors: 
    - Julia Grabinski
    - Paul Gavrikov
    - Janis Keuper
    - Margret Keuper
  link: https://arxiv.org/pdf/2210.05938
  publisher: NeurIPS 22, proceedings of the thirty-sixth Conference on Neural Information Processing Systems 
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2210.05938
    - type: source
      link: https://github.com/GeJulia/robustness_confidences_evaluation
  image: images/neurips_22.png
  tags:
    - CNN
    - robustness    

- title: Trading off Image Quality for Robustness is not Necessary with Regularized Deterministic Autoencoders
  date: 2022-6-1
  authors: 
    - Amrutha Saseendran
    - Kathrin Skubch
    - Margret Keuper
  link: https://pure.mpg.de/rest/items/item_3473164/component/file_3473165/content
  publisher: NeurIPS 22, proceedings of the thirty-sixth Conference on Neural Information Processing Systems 
  extra-links:
    - type: preprint
      link: https://pure.mpg.de/rest/items/item_3473164/component/file_3473165/content
  image: images/neurips_22.png
  tags:
    - robustness
    - VAE


#-------------------------
# 2023
#-------------------------
