# WARNINGS:
# 1) do NOT change month and day at the date -> Bug! Changing the year is fine
# 2) NO ":" in titles -> will break yaml file

#-------------------------
# 2020
#-------------------------
- title: Watch your Up-Convolution - CNN Based Generative Deep Neural Networks are Failing to Reproduce Spectral Distributions
  date: 2020-6-1 
  authors: 
    - Ricard Durall
    - Margret Keuper
    - Janis Keuper
  link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Durall_Watch_Your_Up-Convolution_CNN_Based_Generative_Deep_Neural_Networks_Are_CVPR_2020_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR 2020)
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content_CVPR_2020/papers/Durall_Watch_Your_Up-Convolution_CNN_Based_Generative_Deep_Neural_Networks_Are_CVPR_2020_paper.pdf
    - type: source
      link: https://github.com/cc-hpc-itwm/UpConv
    - typer: youtube
      link: watch?v=s3659tZ4xFs
  image: images/cvpr_20.jpg
  tags:
    - GAN
    - robustness
    - deepfake
  group: AAA

- title: Extracting horizon surfaces from 3D seismic data using deep learning
  date: 2020-6-1
  authors: 
    - Valentin Tschannen
    - Matthias Delescluse
    - Norman Ettrich
    - Janis Keuper
  link: https://library.seg.org/doi/pdf/10.1190/geo2019-0569.1
  publisher: Geophysics - Journal of the Society of Exploration Geophysicists and American Association of Petroleum Geologists
  extra-links:
    - type: preprint
      link: https://library.seg.org/doi/pdf/10.1190/geo2019-0569.1
  image: images/seg.png
  tags:
    - Geophysics
    - CNN
  group: AAA

- title: Detection of point scatterers using diffraction imaging and deep learning
  date: 2020-6-1
  authors: 
    - Valentin Tschannen
    - Matthias Delescluse
    - Norman Ettrich
    - Janis Keuper
  link: https://www.earthdoc.org/content/journals/10.1111/1365-2478.12889?crawler=true&mimetype=application/pdf
  publisher: Geophysical Prospecting
  extra-links:
    - type: preprint
      link: https://www.earthdoc.org/content/journals/10.1111/1365-2478.12889?crawler=true&mimetype=application/pdf
  image: images/gpp_journal.png
  tags:
    - Geophysics
    - CNN
  group: AAA
#-------------------------
# 2021
#-------------------------


- title: An Empirical Investigation of Model-to-Model Distribution Shifts in Trained Convolutional Filters
  date: 2021-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://arxiv.org/abs/2201.08465
  publisher: NeurIPS 21 Workshop - Distribution shifts - connecting methods and applications (DistShift)
  extra-links:
    - type: preprint
      link: https://arxiv.org/abs/2201.08465
  image: images/neurips_22_w.png
  tags:
    - CNN
  group: workshop 
  
- title: Generative models for the transfer of knowledge in seismic interpretation with deep learning
  date: 2021-6-1
  authors: 
    - Ricard Durall
    - Valentin Tschannen
    - Norman Ettrich
    - Janis Keuper
  link: https://pubs.geoscienceworld.org/tle/article-abstract/40/7/534/605879
  publisher: The Leading Edge
  extra-links:
    - type: preprint
      link: https://pubs.geoscienceworld.org/tle/article-abstract/40/7/534/605879
  image: https://library.seg.org/cms/10.1190/leedff.2024.43.issue-1/asset/18ccb341-e318-cb34-3e31-ccb3413e318c/leedff.2024.43.issue-1.cover.png
  tags:
    - Geophysics
    - CNN
  group: journal

- title: SpectralDefense - Detecting Adversarial Attacks on CNNs in the Fourier Domain
  date: 2021-6-1
  authors: 
    - Paula Harder 
    - Franz-Josef Pfreundt
    - Margret Keuper
    - Janis Keuper
  link: https://arxiv.org/pdf/2103.03000
  publisher: IJCNN
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2103.03000
  image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZv9UnCXlR0eTkTM54AwDGP0a4apYHq_NTgA&usqp=CAU
  tags:
    - Robustness
    - CNN
  group: A

- title: Facialgan - Style transfer and attribute manipulation on synthetic faces
  date: 2021-6-1
  authors: 
    - Ricard Durall
    - Jireh Jam
    - Dominik Strassel
    - Moi Hoon Yap
    - Janis Keuper
  link: https://arxiv.org/abs/2110.09425
  publisher: BMVC
  extra-links:
    - type: preprint
      link: https://arxiv.org/abs/2110.09425
  image: https://pbs.twimg.com/profile_images/1596834134126723078/T1xQsNoF_400x400.png
  tags:
    - GAN
  group: A
#-------------------------
# 2022
#-------------------------

- title: Aliasing coincides with CNNs vulnerability towards adversarial attacks
  date: 2022-6-1
  authors: 
    - Julia Grabinski
    - Janis Keuper
    - Margret Keuper
  link: https://openreview.net/pdf?id=vKc1mLxBebP
  publisher: The AAAI-22 Workshop on Adversarial Machine Learning and Beyond
  extra-links:
    - type: preprint
      link: https://openreview.net/pdf?id=vKc1mLxBebP
  image: images/aaai_w.jpg
  tags:
    - robustness
    - CNN
  group: workshop

- title: Is RobustBench/AutoAttack a suitable Benchmark for Adversarial Robustness?
  date: 2022-6-1
  authors: 
    - Peter Lorenz
    - Dominik Strassel
    - Margret Keuper
    - Janis Keuper
  link: https://openreview.net/pdf?id=aLB3FaqoMBs
  publisher: The AAAI-22 Workshop on Adversarial Machine Learning and Beyond
  extra-links:
    - type: preprint
      link: https://openreview.net/pdf?id=aLB3FaqoMBs
  image: images/aaai_w.jpg
  tags:
    - GAN
  group: workshop

- title: Robust Models are less Over-Confident
  date: 2022-6-1
  authors: 
    - Julia Grabinski
    - Paul Gavrikov
    - Janis Keuper
    - Margret Keuper
  link: https://advml-frontier.github.io/pdf/12/CameraReady/ICML_Workshop_Adv_2022.pdf
  publisher: ICML 22 Workshop on NEW FRONTIERS IN ADVERSARIAL MACHINE LEARNING
  extra-links:
    - type: preprint
      link: https://advml-frontier.github.io/pdf/12/CameraReady/ICML_Workshop_Adv_2022.pdf
  image: images/ICML_w.png
  tags:
    - robustness
    - CNN
  group: workshop


  
- title: Aliasing and adversarial robust generalization of CNNs
  date: 2022-6-1
  authors: 
    - Julia Grabinski
    - Janis Keuper
    - Margret Keuper
  link:  https://link.springer.com/article/10.1007/s10994-022-06222-8
  publisher: Machine Learning, Springer 2022
  extra-links:
    - type: preprint
      link: https://link.springer.com/article/10.1007/s10994-022-06222-8
    - type: youtube
      link: watch?v=mM6yhep46R8
  image: images/ml_journal.jpg
  tags:
    - robustness
    - CNN
  group: AAA  
  
- title: Adversarial Robustness Through the Lens of Convolutional Filters
  date: 2022-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://openaccess.thecvf.com/content/CVPR2022W/ArtOfRobust/html/Gavrikov_Adversarial_Robustness_Through_the_Lens_of_Convolutional_Filters_CVPRW_2022_paper.html
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition Workshops (CVPRW 2022)
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content/CVPR2022W/ArtOfRobust/html/Gavrikov_Adversarial_Robustness_Through_the_Lens_of_Convolutional_Filters_CVPRW_2022_paper.html
    - type: source
      link: https://github.com/paulgavrikov/cvpr22w_RobustnessThroughTheLens
    - type: website
      link: https://towardsdatascience.com/what-makes-the-convolutions-of-robust-vision-models-special-5f9c1a0c5bb5
    - type: youtube
      link: watch?v=XzEDIMxpm4Y
  image: images/cvpr_22_w.png
  tags:
    - CNN
    - robustness
  group: workshop

- title: CNN Filter DB - An Empirical Investigation of Trained Convolutional Filters
  date: 2022-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://openaccess.thecvf.com/content/CVPR2022/papers/Gavrikov_CNN_Filter_DB_An_Empirical_Investigation_of_Trained_Convolutional_Filters_CVPR_2022_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR 2022)
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content/CVPR2022/papers/Gavrikov_CNN_Filter_DB_An_Empirical_Investigation_of_Trained_Convolutional_Filters_CVPR_2022_paper.pdf
    - type: source
      link: https://github.com/paulgavrikov/CNN-Filter-DB
    - type: website
      link: https://towardsdatascience.com/what-makes-the-convolutions-of-robust-vision-models-special-5f9c1a0c5bb5
    - type: youtube
      link: watch?v=4CkDvpr2SD4&list=PL4FqEnAZb3YMOTYLpeSaqO2zx-tMgO-oY&index=2
  image: images/cvpr_22_oral.png
  tags:
    - ORAL
    - CNN
    - robustness
  group: AAA


    
- title: FrequencyLowCut Pooling--Plug & Play against Catastrophic Overfitting
  date: 2022-6-1
  authors: 
    - Julia Grabinski
    - Steffen Jung
    - Janis Keuper
    - Margret Keuper
  link: https://arxiv.org/pdf/2204.00491
  publisher: ECCV 2022 - Proceedings of the 17th European Conference, Tel Aviv, Israel
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2204.00491
    - type: source
      link: https://github.com/GeJulia/flc_pooling
    - type: youtube
      link: watch?v=8mgJAB4il_4
  image: images/eccv_22.png
  tags:
    - CNN
    - robustness    
  group: AAA


- title: Physics-informed learning of aerosol microphysics
  date: 2022-6-1
  authors: 
    - Paula Harder
    - Duncan Watson-Parris
    - Philip Stier
    - Dominik Strassel
    - Nicolas R Gauger
    - Janis Keuper
  link: https://www.cambridge.org/core/services/aop-cambridge-core/content/view/C468660D2AEE8E25DC3BF507517FF91A/S263446022200022Xa.pdf/div-class-title-physics-informed-learning-of-aerosol-microphysics-div.pdf
  publisher: Environmental Data Science Journal
  extra-links:
    - type: preprint
      link: https://www.cambridge.org/core/services/aop-cambridge-core/content/view/C468660D2AEE8E25DC3BF507517FF91A/S263446022200022Xa.pdf/div-class-title-physics-informed-learning-of-aerosol-microphysics-div.pdf
  image: images/environmental_data science.jpg
  tags:
    - PINN
    - climate
  group: AAA



- title: Does Medical Imaging learn different Convolution Filters?
  date: 2022-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://arxiv.org/abs/2210.13799
  publisher: NeurIPS 22 Workshop - Medical Imaging meets NeurIPS
  extra-links:
    - type: preprint
      link: https://arxiv.org/abs/2210.13799
  image: images/neurips_22_w.png
  tags:
    - CNN
    - medical imaging
  group: workshop



- title: Robust Models are less Over-Confident
  date: 2022-6-1
  authors: 
    - Julia Grabinski
    - Paul Gavrikov
    - Janis Keuper
    - Margret Keuper
  link: https://arxiv.org/pdf/2210.05938
  publisher: NeurIPS 22, proceedings of the thirty-sixth Conference on Neural Information Processing Systems 
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2210.05938
    - type: source
      link: https://github.com/GeJulia/robustness_confidences_evaluation
  image: images/neurips_22.png
  tags:
    - CNN
    - robustness    
  group: AAA



#-------------------------
# 2023
#-------------------------


- title: Deep diffusion models for seismic processing
  date: 2023-6-1
  authors: 
    - Ricard Durall
    - Ammar Ghanim
    - Mario Fernandez
    - Norman Ettrich
    - Janis Keuper
  link: https://www.sciencedirect.com/science/article/pii/S009830042300081X
  publisher: Computers and Geosciences
  extra-links:
    - type: preprint
      link: https://www.sciencedirect.com/science/article/pii/S009830042300081X
  image: images/cg_journal.png
  tags:
    - geophysics
  group: journal


- title: An Extended Study of Human-like Behavior under Adversarial Training
  date: 2023-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
    - Margret Keuper
  link: https://openaccess.thecvf.com/content/CVPR2023W/AML/papers/Gavrikov_An_Extended_Study_of_Human-Like_Behavior_Under_Adversarial_Training_CVPRW_2023_paper.pdf
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition Workshops (CVPRW 2023)
  extra-links:
    - type: preprint
      link: https://openaccess.thecvf.com/content/CVPR2023W/AML/papers/Gavrikov_An_Extended_Study_of_Human-Like_Behavior_Under_Adversarial_Training_CVPRW_2023_paper.pdf
  image: images/cvpr_23w.png
  tags:
    - robustness
  group: workshop


  
- title: Fine-Grained Product Classification on Leaflet Advertisements
  date: 2023-6-1
  authors: 
    - Daniel Ladwig
    - Bianca Lamm
    - Janis Keuper    
  link: https://arxiv.org/pdf/2305.03706
  publisher: Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition Workshops (CVPRW 2023)
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2305.03706
  image: images/cvpr_23w.png
  tags:
    - retail
  group: workshop


- title: On the Interplay of Convolutional Padding and Adversarial Robustness
  date: 2023-6-1
  authors: 
    - Paul Gavrikov
    - Janis Keuper
  link: https://arxiv.org/pdf/2308.06612
  publisher: Proceedings of the IEEE/CVF International Conference on Computer Vision Workshops (ICCVw 2023)
  extra-links:
    - type: preprint
      link: https://arxiv.org/pdf/2308.06612
  image: images/ICCVw23.jpg
  tags:
    - robustness
  group: workshop



- title: An In-Depth Study of U-net for Seismic Data Conditioning - Multiple Removal by Move-Out Discrimination
  date: 2023-6-1
  authors: 
    - Ricard Durall
    - Ammar Ghanim
    - Norman Ettrich
    - Janis Keuper
  link: https://library.seg.org/doi/pdf/10.1190/geo2023-0146.1
  publisher: Geophysics - Journal of the Society of Exploration Geophysicists and American Association of Petroleum Geologists
  extra-links:
    - type: preprint
      link: https://library.seg.org/doi/pdf/10.1190/geo2023-0146.1
  image: images/seg.png
  tags:
    - Geophysics
    - CNN
  group: journal

- title: Improving Native CNN Robustness with Filter Frequency Regularization
  date: 2023-6-1
  authors: 
    - Jovita Lukasik
    - Paul Gavrikov
    - Janis Keuper
    - Margret Keuper
  link: https://openreview.net/forum?id=2wecNCpZ7Y
  publisher: Geophysics - Journal of the Society of Exploration Geophysicists and American Association of Petroleum Geologists
  extra-links:
    - type: preprint
      link: https://openreview.net/forum?id=2wecNCpZ7Y
  image: https://jmlr.org/tmlr/img/tmlr.jpg
  tags:
    - Robustness
    - CNN
  group: journal 
